### PR TITLE
Add starter element and gulp task el

### PR DESCRIPTION
**Pull request by chuckh**
You can create a new element by doing `gulp el —new my-element`.  This example will create a new folder under elements called `my-element ` and create a file called `my-element.html` in this folder.  `my-element` is based off `app/elements/starter-element.html`. 

Run `npm install` to install new dependency of minimist.

The purpose of this pr is to make it simpler to create a new basic element. I will update the readme.md with instructions if the team thinks we should add this. What do you think: @addyosmani, @arthurvr, @samccone?

### CODE REVIEW

**Comment by addyosmani** [comment]
Thanks a lot for working on this @chuckh. I'm a little torn on whether we should go in this direction. On one hand, I can see the utility value of just being able to run another task to create an element. On the other, this seems to overlap directly with scaffolding functionality we would normally tell folks to just use Yeoman for (via generator-polymer). My concern is setting a precedent for us adding in features we already have another tool for. Any thoughts? cc'ing in @robdodson for his take on this too.

**Comment by arthurvr** [comment]
It's of course up to the team to decide this, but I feel like this really is reinventing the wheel. Yeoman does this perfectly and is created especially for things this. I also feel like Yeoman does it significantly better (the prompting, config, Yeoman generators are easily forkable, ...)

**Comment by chuckh** [comment]
The reason I created this pr:

1. Since PSK has been release I have found myself not use yeoman anymore (used it a lot with Polymer < 1.0). ***One less tool to maintain***. Instead I just created a starter-element that I would manually copy when creating a new element. This just just automated the process some.
2. When I reviewed the PSK tutorial section to *Create a new element* that Kayce is working on, it seemed more complicated then needed. See https://raw.githubusercontent.com/kaycebasques/docs/psk/1.0/docs/start/psk.md Create a new element section
3. To show a method of using separate gulp task file, keeping gulpfile.js lighter. We might want to use this method for recipes like ***Adding an ES2015 recipe*** see https://github.com/PolymerElements/polymer-starter-kit/pull/333#discussion_r38106827, or deploying to GAE recipe see https://github.com/StartPolymer/polymer-starter-kit-plus/blob/master/gulp-tasks/deploy.js, or deploying to Firebase recipe see https://github.com/StartPolymer/polymer-starter-kit-plus/blob/master/gulp-tasks/deploy.js
4. To start a dialog about this approach

I am fine with whatever outcome the team thinks is best:  include in main PSK, making it a recipe, or not using it at all.

**Comment by arthurvr** [comment]
> One less tool to maintain.

If you mean something like this can replace Yeoman I think you're forgetting quite a bit of Yeoman's features and usecases. Just to give a few super easy examples, the Yeoman generator fills in [dependencies](https://github.com/yeoman/generator-polymer/blob/master/el/templates/element.html#L12) and the [element name](https://github.com/yeoman/generator-polymer/blob/master/el/templates/element.html#L28). It even has a GUI app.

Besides from that, I think the code inside of `gulp-tasks/el.js` shouldn't live in one's project but in the Yeoman generator (or in their fork if that's needed). Separation of concerns, right? Things like this are usable in so many projects that I don't see the point of repeating it in many projects, it's better to use already existing tooling (like Yeoman) therefore. 

> Instead I just created a starter-element that I would manually copy when creating a new element. This just just automated the process some.

That automation is exactly what Yeoman does and is meant to do. I still don't see why we'd reinvent the wheel. 

> To show a method of using separate gulp task file, keeping gulpfile.js lighter.

:+1: Although, our gulpfile is still relatively small so I personally don't think that's needed yet.

**Comment by JosefJezek** [comment]
We have snippets, check out the link https://github.com/robdodson/Atom-PolymerSnippets

**Comment by robdodson** [comment]
The Polymer generator should recognize the PSK structure and allow you to quickly create an element using [the `el` subgenerator](https://github.com/yeoman/generator-polymer#element-alias-el). In the latest release it should also scaffold out a test for you if you want it. My (totally biased vote :smile_cat:) is to keep this kind of stuff in a generator and keep the gulpfile as small as possible.

**Comment by chuckh** [comment]
Thanks everyone for your consideration and thoughtful feedback. I agree this is better handled by Yeoman Generator for Polymer. So I'm going to close this pr. 

We may want to consider updating the readme.md at https://github.com/PolymerElements/polymer-starter-kit/#yeoman-support suggesting to use Yeoman Generator for Polymer as the recommended way to get and work with PSK.

@robdodson nice working on adding the `tests` and `--docs` to the generator.

**Comment by robdodson** [comment]
ah i can't take credit for those, they came in as PRs from the community.
Open source FTW! :)

**Pull request closed without merging**
