### PR TITLE
Add ESLint support

### PR DESCRIPTION
**Pull request by abdonrd**

### CODE REVIEW

**Comment by robdodson** [comment]
I think we're still trying to figure out what we want our gulp support to look like. What we want to avoid is the crazy gulpfile that is currently in PSK1. Our current thinking is to break each gulp task into its own module and use a similar approach to the one used in wsk2. https://github.com/google/web-starter-kit/tree/wsk2/src

We could see about doing something like that with this eslint task maybe?

**Comment by abdonrd** [comment]
Makes sense! I will update. :)

**Comment by abdonrd** [comment]
@robdodson updated! :sparkles:

**Comment by chuckh** [comment]
:+1:

**Comment by robdodson** [comment]
I'm wondering if it would be possible to use the same gulpfile approach as WSK does here https://github.com/google/web-starter-kit/blob/wsk2/src/gulpfile.js

Using require-dir makes all of the gulp tasks mandatory but I think we may want to make it clear which ones are being used, and use the same configuration approach as WSK. That way users can have a bit more control over the behavior of the gulpfile

**Comment by abdonrd** [comment]
@robdodson sounds good to me. And we avoid one more npm dependency. :) Check it now.

I code:

```javascript
require('./gulp-tasks/lint.js');
```

Instead of:

```javascript
var lint = require('./gulp-tasks/lint.js');
```

To avoid the `no-unused-vars` error, because nobody will use the `lint` var.

**Comment by abdonrd** [comment]
@robdodson updated and rebased! :)

**Comment by chuckh** [comment]
LGTM. Nice work @abdonrd!

**Comment by robdodson** [comment]
Was off filming stuff today but I'll try to review this in the morning. Thanks for updating the PR @abdonrd :D

**Comment by abdonrd** [comment]
Your welcome! :)

ESLint support will be nice in PSK2! :grin:

**Comment by abdonrd** [comment]
Friendly ping to @robdodson. :)

**Comment by robdodson** [comment]
@justinfagnani how would you like us to proceed on this?

**Comment by justinfagnani** [comment]
Can we add JS linting to `polytool lint`? Contributions welcome :)

**Comment by robdodson** [comment]
@justinfagnani we can I guess.. how should we decide which files to source? At present they're done like this in the gulpfile https://github.com/PolymerElements/polymer-starter-kit/pull/779/files#diff-742af4f7ce30ade9ca8aab1f4046729cR18

**Comment by abdonrd** [comment]
Now I can't contribute much in the polylint, because I don't how it works. 😅

**Comment by abdonrd** [comment]
But then... `polytool` will manage all the linting? `ESLint` + `PolyLint`?

**Comment by robdodson** [comment]
@abdonrd I guess that's the plan. @justinfagnani there may be some thing which don't make sense as polytool commands, do you have an example of a project gulpfile that gets run as part of polytool?

**Comment by addyosmani** [comment]
One thing we probably want to sanity check if we do add ESLint support to `polytool` is that ESLint configuration is still low-friction for folks and picks up rules from `.eslintrc`/`package.json` etc. Anywhere they're likely to try configuring these pieces.

**Comment by justinfagnani** [comment]
Let's chat about linting this week. Maybe JS linting doesn't belong in polylint? Polytool can certainly get the hook for retrieving all the files it cares about, for use in a gulfile say. This includes splitting script from HTML if necessary.

**Comment by abdonrd** [comment]
@justinfagnani yes, I think that `polylint` only lint Polymer. But `polytool lint`, could have `polylint`plus another configurable (by gulp tasks?) linters (like `eslint`).

**Comment by abdonrd** [comment]
@justinfagnani any news about how to opt-in the `eslint` to the Polymer CLI lint (`polymer lint`)? Thanks in advance!

**Comment by abdonrd** [comment]
PR updated! @robdodson @chuckh PTAL :)

**Comment by robdodson** [comment]
@justinfagnani do you think this is how you'd like something like ESLint used or would you prefer to see it go through the splitHTML pipeline simile to the way we do imagemin?

**Comment by abdonrd** [comment]
Friendly ping to @justinfagnani. :)

**Comment by abdonrd** [comment]
@robdodson @chuckh @justinfagnani updated with the latest PR (https://github.com/PolymerElements/polymer-starter-kit/pull/886): Update to polymer-build v0.3.0

**Comment by abdonrd** [comment]
After thinking about that, maybe we need to update the tasks with `module.exports` as the [google/web-starter-kit](https://github.com/google/web-starter-kit/tree/wsk2/src)?

**Comment by abdonrd** [comment]
Closed in favor to [PolymerElements/generator-polymer-init-custom-build](https://github.com/PolymerElements/generator-polymer-init-custom-build).

**Pull request closed without merging**
