### PR TITLE
Removes force-narrow and enhances layout for desktop

### LINKED ISSUE #59: Consider not using forceNarrow on desktop
https://www.polymer-project.org/1.0/docs/start/getting-the-code.html is great - left hand nav is very responsive, collapses and expands as I change the browser width.  I want that for the starter kit - responsive design out of the box!

Current:
Run app locally
Enlarge window
Menu *doesn't* responsively become a left hand nav

### PR DESCRIPTION
**Pull request by chuckh**
### This pull request will:
1. removes force-narrow which shows nav drawer for tablets and desktops
1. darkens drawer toolbar background
1. adds box-shadow to drawer for desktop and landscape tablet layout
1. adds margin to content for tables and dekstops

### Phone / portrait tablet layout
image

image

### Desktop and landscape tablet layout
image

### CODE REVIEW

**Comment by addyosmani** [comment]
Some context for the newer commits: we received feedback from the Material Design team that they felt the mismatch in headers, height and colour of the current iteration felt a little weird. Their suggestion was to match the spec closer. 

I believe Chuck's most recent commits get us really close. We've sent this over to the team for a second review and will update once we've heard from them.

**Comment by chuckh** [comment]
The latest commits revise layout to be similar to http://www.google.com/design/spec/material-design/introduction.html per initial feedback from Material Design team.

### Desktop / Tablet 
image

### Desktop / Tablet  toolbar shrunk
image

### Mobile Portrait
image

**Comment by addyosmani** [comment]
Got the go ahead from design. Would you like to rebase your PR against master @chuckh and we can land this?

**Comment by chuckh** [comment]
@addyosmani yes.

**Comment by chuckh** [comment]
I have rebased the PR against master @addyosmani.

**Comment by addyosmani** [comment]
Landed via 3759adce1a0af9f1e3497d69b5c022c1f89f6290

**Pull request closed without merging**
