### PR TITLE
Moving style tags to inside of template

### PR DESCRIPTION
**Pull request by alexpaluzzi**
New perf recommendation in v1.1

### CODE REVIEW

**Comment by alexpaluzzi** [comment]
*Previously, we recommended that a `<style>` element should be placed inside an element’s `<dom-module>` but outside of its template. This is still supported, but we’ve now optimized placing styles within the template itself, so having the `<style>` tag outside of the template will be slower. We will be updating all of the elements provided by the Polymer team to match this new recommended behavior as well.*

https://blog.polymer-project.org/announcements/2015/08/13/1.1-release/

**Comment by alexpaluzzi** [comment]
closing/reopening to re-run checks (non-code fail)

**Comment by alexpaluzzi** [comment]
@addyosmani Not entirely sure why the check VM errored out, but it shouldn't be code related. Can we run again?

**Comment by addyosmani** [comment]
I don't think the CI failure has anything to do with this PR. Merging away as is.

**Pull request closed without merging**
