### PR TITLE
Use HTTPS

### PR DESCRIPTION
**Pull request by FluorescentHallucinogen**

### CODE REVIEW

**Comment by jsilvermist** [comment]
Note: I believe that if these license headers are changed they will be doubled as they won't be deduplicated against the headers from all Polymer elements when building/bundling without changing those as well.

**Comment by FluorescentHallucinogen** [comment]
@jsilvermist What do you mean? All comments (license headers) are stripped during build process.

**Comment by jsilvermist** [comment]
I believe there's an exception for jsdoc comments beginning with `@license`, which are duplicated but not completely removed.

**Comment by abdonrd** [comment]
Thanks @FluorescentHallucinogen, but @jsilvermist is right!

**Pull request closed without merging**
