### PR TITLE
Ask to be linted as a hybrid app

### PR DESCRIPTION
**Pull request by rictic**
Part of the unreleased, configurable, new linter. More info: Polymer/polymer-cli#566

### CODE REVIEW

**Comment by robdodson** [comment]
Should we wait till the linter is released to merge this?

**Comment by rictic** [comment]
Your call. It causes no harm, extra properties in polymer.json will always be ignored. Storing the configuration here means that we can more easily run the new linter against psk in its integration tests.

The new linter will be merged shortly, though it will be under an alternative command while we port the rest of the lint rules from polylint, so it'll be run as something like `polymer experimental-lint`

**Comment by robdodson** [comment]
could we do the change on the 2.0-preview branch of PSK instead? would your tests still be able to run against that?

**Comment by rictic** [comment]
Yep, that'll work!

**Pull request closed without merging**
