### PR TITLE
Add travis config

### PR DESCRIPTION
**Pull request by samccone**
~~pending on someone to flip this switch~~
~~https://travis-ci.org/profile/PolymerElements~~

### CODE REVIEW

**Comment by robdodson** [comment]
I'm not well versed in teh before_script commands being sent to travis but otherwise lgtm :D

**Comment by samccone** [comment]
oh sorry this is not done just yet..... give me 20 min :dancer: I got side tracked yesterday

**Comment by samccone** [comment]
All set @robdodson @addyosmani 

yay back to green!

**Comment by robdodson** [comment]
sure lgtm :D

**Pull request merged**
