### PR TITLE
Use Superstatic + firebase.json for URL rewriting

### PR DESCRIPTION
**Pull request by mbleigh**
This PR makes some changes likely to have varying degrees of controversy:

1. Use Superstatic as the static web server for URL rewrites
2. Add a `firebase.json` (without app name) to the root (this is picked up by Superstatic)
3. Prefer absolute URLs in `index.html` over `<base>` tag
4. Default to pushState routing over hashbangs
5. Update Firebase deploy guide based on changes

Feedback? kthxbai :cat:

### CODE REVIEW

**Comment by robdodson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robdodson** [comment]
This seems awesome to me. Local pretty URLs is a nice touch.

Some things to think about:

- If someone deploys to GitHub pages, or any other server that's not configured to always serve index.html they'll need to flip hashbangs back on and we'd need to document that.
- We could remove the firebase.json added to the `docs` directory by https://github.com/PolymerElements/polymer-starter-kit/pull/584
- The absolute URLs in `<head>` are tricky for folks serving from a subdirectory (like GH Pages). The docs for `<base>` say it only works for relative URLs. (I spoke with @mbleigh, we agreed to try to add a `<base>` element instead so it's easier to update our recipes)

**Comment by mbleigh** [comment]
Switched to `<base>` but I'd argue in favor of keeping the `firebase.json` -- for one, it's used by Superstatic to pick up the configuration for rewrites. For another, it means that people just have to add one line and type `firebase deploy` to get it up on Firebase.

Switching to pushState by default will mean needing documentation for deploying to non-pushstate-able servers. I think pushState should be the default, though (esp. since hashbangs are considered deprecated by Google search crawlers).

**Comment by robdodson** [comment]
> I'd argue in favor of keeping the firebase.json -- for one, it's used by Superstatic to pick up the configuration for rewrites. For another, it means that people just have to add one line and type firebase deploy to get it up on Firebase.

Oh yeah we'd keep the `firebase.json` you added. I meant we wouldn't include a 2nd one in the docs directory. Does that make sense?

**Comment by mbleigh** [comment]
Yes, totally!

**Comment by robdodson** [comment]
> Switching to pushState by default will mean needing documentation for deploying to non-pushstate-able servers. I think pushState should be the default, though (esp. since hashbangs are considered deprecated by Google search crawlers).

Yeah agreed. I'm all for getting folks on the right path

**Comment by samccone** [comment]
@robdodson do you think this PR increasing the barrier to entry or decreasing it?

**Comment by robdodson** [comment]
I don't see it as increasing the barrier. A significant portion of devs I talk to are already using PSK with Firebase so that part gets easier. For folks who aren't, it demonstrates how to do a SPA that doesn't rely on hashbangs which are a deprecated pattern at this point.

I do think it probably warrants a major version number rev though. But my hope is that for most folks this is a transparent change.

**Comment by samccone** [comment]
Word, the push state routing default  was the big concern for me just because it does add a certain level of magic to things :)

**Comment by chuckh** [comment]
I agree with moving to pushState by default. We will also need to update:

1. travis-runner.sh to handle this for the auto deploy to GitHub pages
2. Deploy to Github Pages https://github.com/PolymerElements/polymer-starter-kit/blob/master/docs/deploy-to-github-pages.md

**Comment by robdodson** [comment]
@addyosmani are you around this week to chat about this?

**Comment by addyosmani** [comment]
@robdodson I am! 

> Switching to pushState by default will mean needing documentation for deploying to non-pushstate-able servers. I think pushState should be the default, though (esp. since hashbangs are considered deprecated by Google search crawlers).

:+1:

**Comment by samccone** [comment]
@addyosmani let me know if there is anything I can do here to help :wave:

**Comment by mbleigh** [comment]
Likewise me :wave: :wolf:

**Comment by addyosmani** [comment]
1. Will pushState by default (with it's magic) likely confuse users who don't have push-stateable servers? (Seems yes)
2. Are we content with moving ahead with it as a default assuming we can get a PR for docs for the non-pushState use case? - anyone want to write those docs? :)

**Comment by robdodson** [comment]
> Will pushState by default (with it's magic) likely confuse users who don't have push-stateable servers? (Seems yes)

In particular this is the GitHub pages crowd. But page.js hash routing is super buggy so we're not in an awesome place there either. @mbleigh does super static support hash urls as an option?

> Are we content with moving ahead with it as a default assuming we can get a PR for docs for the non-pushState use case? - anyone want to write those docs? :)

Yeah if there's an easy enough fallback (maybe just swapping back to the old connect server and adding `hashbang: true` to the `page()` call in `routing.html`

**Comment by mbleigh** [comment]
Since hash routes are all client side no reason superstatic can't support.
You'd just want to remove the rewrite from the config.

**Comment by chuckh** [comment]
As a reminder the follow will also need to be updated for auto deploys to work after this pr is merged.

1. travis-runner.sh to handle this for the auto deploy to GitHub pages at https://github.com/PolymerElements/polymer-starter-kit/blob/master/travis-runner.sh#L13
 1. will need to set `hashbang: true`
 2. then test and make other possible fixes
3.  travis-runner.sh to handle this for the auto deploy to Firebase at https://github.com/PolymerElements/polymer-starter-kit/blob/master/travis-runner.sh#L26
 1. remove lines https://github.com/PolymerElements/polymer-starter-kit/blob/master/travis-runner.sh#L30-L31
 2. @mbleigh will this line still be needed? https://github.com/PolymerElements/polymer-starter-kit/blob/master/travis-runner.sh#L32

Also the Deploy to Github Pages recipe:  https://github.com/PolymerElements/polymer-starter-kit/blob/master/docs/deploy-to-github-pages.md will need to be updated to reflect these changes.

**Comment by mbleigh** [comment]
@chuckh quite possibly. There is also official support for Firebase deploy baked into Travis now. See [this .travis.yml](https://github.com/staticapps/staticapps.org/blob/master/.travis.yml) for an example of the format needed.

**Comment by abdonrd** [comment]
Any news?

**Comment by robdodson** [comment]
I think the Polymer CLI is going to use polyserve as its local server. I'm wondering, with that in mind, if it makes sense to include a server at all with PSK2?

I would like to be able to support pretty urls instead of having to use hash routes. @justinfagnani is something like that in the cards for polyserver/Polymer CLI?

**Comment by justinfagnani** [comment]
@robdodson definitely thinking about how to support pretty URLs in polyserve/polytool. No definite plans yet though.

**Comment by robdodson** [comment]
Now that we've switched over to PSK2 and relying on Polymer CLI as our server, I think I'm going to close this and recommend that we build a separate generator, specifically targeted at Firebase + Polymer integration. This would also give us an opportunity to really show off Polymerfire and a bunch of the other Firebase features. Explained here as well https://github.com/PolymerElements/polymer-starter-kit/issues/512#issuecomment-242927182

**Comment by mbleigh** [comment]
SGTM

**Pull request closed without merging**
