### PR TITLE
Add polymer 1.1.0 dependency, move style under template

### PR DESCRIPTION
**Pull request by chuckh**
To have PSK install Polymer 1.1 I had to add dependency to bowler.json.

@addyosmani please review

### CODE REVIEW

**Comment by chuckh** [comment]
Problems fixing conflicts. So closing this pull request. Will create a new one with out conflicts.

**Comment by addyosmani** [comment]
Sounds good. Thanks!

**Comment by arthurvr** [comment]
> Problems fixing conflicts. So closing this pull request. Will create a new one with out conflicts.

No need to create a new PR. Makes it really noisy and you can fix conflicts using a rebase on this PR ;)

**Comment by chuckh** [comment]
@arthurvr sorry about that. I did not have any luck fix conflicts with rebasing. I created new pr yesterday #311. It does not have any conflicts. I will try to avoid in the future.

**Pull request closed without merging**
