### PR TITLE
Rev html-extract and add strip option

### PR DESCRIPTION
**Pull request by robdodson**
I can't recall if the caret will pick up a minor rev like this so i upticked the version just in case

### CODE REVIEW

**Comment by samccone** [comment]
(can we turn the rule back on :))

**Comment by robdodson** [comment]
I guess sooooooo

I turned it back on and rebased. I think I need to update the ES2015 recipe because it fails for other jscs reasons (spaces around the function parens i think). I'll do a separate PR for that

**Comment by robdodson** [comment]
oh hold on let me fix the whitespace rule as well

**Comment by robdodson** [comment]
nvm, I was thinking of the EOL rule. The whitespace rule was already in there. I think we're good to merge.

**Comment by samccone** [comment]
boom

**Comment by robdodson** [comment]
actually the es2015 recipe looks like it's passing. You just have to be careful how you delete the `+` signs so you don't end up with the wrong indentation.

**Pull request merged**
