### PR TITLE
Changes to deploy PSK2 to GitHub pages

### PR DESCRIPTION
**Pull request by chuckh**
**Don't merge this Pull Request**. It is here for reference for deploying PSK2 to GitHub Pages.

### CODE REVIEW

**Comment by chuckh** [comment]
Besides these changes I had to manually copy `images` folder to `build/bundled folder`.

**Comment by TimvdLippe** [comment]
I think this is also blocked on https://github.com/Polymer/polymer-cli/issues/273. When I tried to deploy to GitHub pages, I got a lot of problems since the subdirectory was ignored. This is probably also the reason all absolute paths have to be changed to be relative.

**Comment by FluorescentHallucinogen** [comment]
Any progress?

**Comment by joeblew99** [comment]
thanks @chuckh 

@TimvdLippe  i also need relative paths, so really good to see this change coming through.
I have been using polymer with electron and cordova, and absolute paths cause cordova to have a bad day.  

So this change is good for many things. Makes it much easier to use to build desktop and mobile apps.

**Comment by TimvdLippe** [comment]
@chuckh you might be able to fix the issue with the new `--root` option, see https://github.com/Polymer/polymer-cli/issues/273#issuecomment-245687196

**Comment by robdodson** [comment]
agree we should switch to relative paths for everything. If anyone wants to do a PR for just that one change that would be apprecaited!

**Comment by FluorescentHallucinogen** [comment]
Any progress?

**Comment by FluorescentHallucinogen** [comment]
Please see also https://github.com/Polymer/shop/issues/73.

**Comment by joeblew99** [comment]
can this be merged now ?

**Comment by chuckh** [comment]
Sorry I have not been able to get back to this PR. Working on a big project that has taken all of my time.

This PR should never be merged. I created it for people to reference for deploying to GitHub.  What should happen:

1. A PR for relative paths should be created for PSK.
2. A separate custom-build-github should be created to add the additional changes for deploying to GitHub pages (similair to https://github.com/chuckh/generator-polymer-init-custom-build-gae).
3. This PR should then be closed

**Comment by chuckh** [comment]
Just created PR #940 for 1. relative paths.

**Comment by chuckh** [comment]
@joeblew99 @FluorescentHallucinogen PR #940 that changes PSK to relative paths has been merged into master.  This should help with Cordova.

**Comment by robdodson** [comment]
Is anyone interested in kicking off that GH pages custom build generator..?

**Comment by robdodson** [comment]
Would it be ok to close this PR? It's not something we're planning on merging (it's more meant as a reference) but it might ultimately be better to create a separate generator for GH pages

**Comment by chuckh** [comment]
I agree, closing.  I hope to get sometime around the end of January to create generator for GH pages depending on when Polymer 2.0 is released.

**Pull request closed without merging**
