### PR TITLE
Fix paper-header-panel mode

### PR DESCRIPTION
**Pull request by tominon**

### CODE REVIEW

**Comment by tominon** [comment]
I signed it!

**Comment by flaiker** [comment]
I think this conflicts with #233.

**Comment by addyosmani** [comment]
I've landed #233 as we're currently moving away from directly using paper-header-panel to using it's successor for the types of scroll interaction PSK's layout requires paper-scroll-header-panel. Afaik, this fix is no longer needed. Could you confirm?

(Also, thanks a lot for the PR. We appreciate the help!)

**Comment by robbbz** [comment]
Need of a rebase.

**Comment by chuckh** [comment]
Now that we are using `paper-scroll-header-panel` we can now close this. `paper-scroll-header-panel` does not support mode per docs at https://elements.polymer-project.org/elements/paper-scroll-header-panel?view=docs&active=paper-scroll-header-panel.

**Pull request closed without merging**
