### PR TITLE
[master/polymer-1] Simpler differential serving & non-root-paths

### PR DESCRIPTION
**Pull request by jsilvermist**
Polymer 1 parody of #1030.

### CODE REVIEW

**Comment by jsilvermist** [comment]
The `url-space-regex="[[rootPath]]*"` was causing the error:
```
Uncaught SyntaxError: Invalid regular expression: /*/: Nothing to repeat
```
This error doesn't seem to be present on `2.0-preview`, but won't it still just be repeating the last `/`?

**Comment by jsilvermist** [comment]
`iron-location`'s `_urlSpaceRegExp` property is equal to `/\/.*/` after this change, so it seems to be properly escaping the `/`.

On `2.0-preview` it's `/\/*/`, should I create a PR to also change this on `2.0-preview`?

**Comment by graynorton** [comment]
Thanks, @jsilvermist. I have to admit that I didn't scrutinize the expression -- I lifted it straight from @arthurevans's example and did only a very cursory check to make sure that nav links weren't entirely broken. :-P

Looking at the docs for `url-space-regex`, it seems like just `/^[[rootPath]]/` (i.e., `url-space-regex="^[[rootPath]]"` ought to work.

Yes, please do file a corresponding PR against `2.0-preview` as well.

**Comment by arthurevans** [comment]
Yep, my bad, I kind of just poked at it. app-location docs say:
            
This regexp is given everything after the origin in an absolute
URL. So to match just URLs that start with /search/ do:
     url-space-regex="^/search/"

Which suggests that `"^[[rootPath]]"` should work for rootPaths like `"/"` `"/foo/"` or `""`.

**Comment by jsilvermist** [comment]
Updated this and sent PR for `2.0-preview` fix at #1032.

**Pull request merged**
