### PR TITLE
Set firefox to latest for travis

### PR DESCRIPTION
**Pull request by chuckh**
as Selenium - Firefox issue is now fixed SeleniumHQ/selenium#2110.

### CODE REVIEW

**Comment by robdodson** [comment]
Cool. Feels like we should add firefox to the test matrix. I think right now it's only running tests against chrome

**Comment by chuckh** [comment]
So for now we need to leave `firefox: `46` otherwise tests will not run. I think it is related to this issue: https://github.com/Polymer/web-component-tester/issues/367.

**Comment by robdodson** [comment]
Looks like Polymer/web-component-tester#367. Maybe we can try again with the latest FF?

**Comment by chuckh** [comment]
@robdodson changed firefox to latest and tests passed!

**Comment by robdodson** [comment]
awwwwwww yissssssss

**Pull request merged**
