### PR TITLE
Add .DS_Store to .gitignore for OSX user

### PR DESCRIPTION
**Pull request by timwangdev**

### CODE REVIEW

**Comment by timwangdev** [comment]
I signed it!

**Comment by abdonrd** [comment]
I think that the `.DS_Store` should be in the `.gitignore_global`.

**Comment by timwangdev** [comment]
See also #469

**Comment by samccone** [comment]
+1 for adding to your personal global ignore

will leave the final call up to @addyosmani

**Comment by timwangdev** [comment]
@abdonrd @samccone I admit that adding `.DS_Store` to `.gitignore_global` would be more reasonable. I'll close this one.

**Comment by samccone** [comment]
thanks for the idea though @timwangdev :)

**Pull request closed without merging**
