### PR TITLE
Fix broken dist. Close #564

### LINKED ISSUE #564: Fix whatever's up with iron-flex-layout
Related to https://github.com/PolymerElements/polymer-starter-kit/pull/563

I'm looking into this with @notwaldorf 

cc @samccone @chuckh @addyosmani 

To repro:

Delete [this line](https://github.com/PolymerElements/polymer-starter-kit/blob/master/bower.json#L12) from `bower.json`.

Run `gulp serve` to see the normal version. Then run `gulp serve:dist` to see the broken version.

### PR DESCRIPTION
**Pull request by robdodson**
Revert 7e4b99 and 967aae

@samccone @chuckh @addyosmani PTAL

### CODE REVIEW

**Comment by chuckh** [comment]
LGTM. Tested worked on Chrome, Firefox and Safari.  Did not fix IE 11 and Edge issue #550.

**Comment by samccone** [comment]
before we merge (revert), @robdodson any thoughts around the origin issue of vulcanize not minifying inlined style rules?

Perhaps we should file a bug in vulcanize or try and get a cohesive story together for people about this

**Comment by robdodson** [comment]
@samccone yeah [as i mentioned](https://github.com/PolymerElements/polymer-starter-kit/issues/564#issuecomment-162041607) the polymer team is aware of it and writing their own CSS parser to handle it.

My advice would be to not try to minify CSS until that parser comes out, and just let gzip do what it can. But I'll defer to @azakus and @cdata

**Comment by samccone** [comment]
kk I have opened an issue to track this better :)

thanks for all of the info and investigation work @robdodson 

---

@chuckh on a related note, perhaps we should consider adding screenshot tests to our CI process to make sure these kind of regressions do not pop up

thoughts?

**Comment by chuckh** [comment]
@samccone screenshot testing would be great. :+1: :100:  Have you done that before?  Can we model from some other project?

**Pull request merged**
