### PR TITLE
Remove ES6 support from JSHint.

### PR DESCRIPTION
**Pull request by nicolasgarnier**
JS6 support is now handled as part of of a recipe. See #333.

### CODE REVIEW

**Comment by arthurvr** [comment]
lgtm

**Comment by goldieep** [comment]
@arthurvr please merge this look good to me
i demand this to be merged soon

**Comment by arthurvr** [comment]
I can't merge this, and being demanding won't get you anywhere in open source, or life.

**Comment by addyosmani** [comment]
:+1:

**Pull request merged**
