### PR TITLE
Rename to sources and extraDependencies

### LINKED ISSUE #975: polymer.json
Rename sourceGlobs and includeDependencies to sources and extraDependencies.

### PR DESCRIPTION
**Pull request by abdonrd**
Fix #975

First, we need wait to the Polymer CLI v0.18.0 release:
https://github.com/Polymer/polymer-cli/releases

### CODE REVIEW

**Comment by stramel** [comment]
These changes are also in #967

**Comment by abdonrd** [comment]
@stramel yes! But to release the `2.0-preview`, we need to wait Polymer 2.0.

**Comment by stramel** [comment]
@abdonrd guess I should have left mine(#973) open then lol

**Comment by abdonrd** [comment]
@stramel probably 😅

**Comment by stramel** [comment]
@abdonrd Noticed this when running the `--verbose` mode. 

image

Even when using `"bower_components/webcomponentsjs/*.js"` it still shows duplicate. I think it is probably an issue upstream in `polymer-build`

**Comment by abdonrd** [comment]
Thanks @stramel! Ping to @FredKSchott. 😃

**Comment by abdonrd** [comment]
Now with the [Polymer CLI v0.18.0](https://github.com/Polymer/polymer-cli/pull/663) release we can merge this.

@FredKSchott can you review https://github.com/PolymerElements/polymer-starter-kit/pull/976#issuecomment-293134096 before merging?

**Comment by FredKSchott** [comment]
@stramel oh yea, I think we added a workaround to always include "bower_components/webcomponentsjs/*.js" because it was so easy to forget. I would keep the polymer.json file as-is though, it's good to be explicit and the file stream should do the right thing and de-dupe.

@abdonrd lets hold off until v0.18.0 has been released to `latest`, currently shooting to get that done tomorrow

**Comment by stramel** [comment]
@fredkschott LGTM :+1:

**Pull request merged**
