### PR TITLE
Add Auto Deploy to Firebase

### PR DESCRIPTION
**Pull request by chuckh**
Replaces pr #584 and addresses auto deploy part of issue #583.  PTAL @robdodson.

### CODE REVIEW

**Comment by robdodson** [comment]
annoying question... does the json file need to live in /docs or could it live in the directory with the firebase recipe?

**Comment by chuckh** [comment]
Well... the recipe `deploy-to-firebase-pretty-urls.md` does live in the /docs directory.  We moved it there so it would not interfere with a new user wanting to use Firebase and running `firebase init`.

**Comment by robdodson** [comment]
ohhh! my bad. I thought each recipe had its own directory within /docs (now i kind of wish they did so if there are extra files they could live with the recipe).

**Comment by robdodson** [comment]
Not a blocker for this though. It LGTM, I'll let @samccone make the final call as he's more familiar with the travis stuff

**Comment by addyosmani** [comment]
LGTM

**Pull request merged**
