### PR TITLE
Update webcomponent polyfill check to use ES6

### PR DESCRIPTION
**Pull request by stramel**
I made these separate commits for now so  I can easily revert any of them. I will squash before the merge if requested.

The following items were addressed:

- Updated webcomponent polyfill check to use ES6.
- Updated polymer to be even more lazy using the `lazyLoad: max` and `useNativeCSSProperties: true`.
- Updated the app import to be asynchronous. (Noticed this on a few Google projects)
- Updated the webcomponent polyfill check to be at the bottom of the body. (Noticed this on a few Google projects)

Happy to address any feedback! Thanks for the awesome app starting point!

### CODE REVIEW

**Comment by stramel** [comment]
I have signed the CLA with a different account previously. I have added this email to that one under and alternate email but it is still showing `cla: no`

**Comment by admwx7** [comment]
:+1:

**Comment by robdodson** [comment]
Because IE11 doesn't have support for arrow functions I'd like to hold off on the ES6 change. I *think* we could use const without it complaining but I need to double check (unless someone else has a PC handy).

**Comment by abdonrd** [comment]
And why moving the styles and html import?

**Comment by admwx7** [comment]
@robdodson this is going into the 2.0 preview which uses the ES6 class syntax for creating elements, which isn't supported in IE11 either.

**Comment by robdodson** [comment]
@admwx7 ah didn't notice that, thanks :)

**Comment by stramel** [comment]
@abdonrd I'm not entirely sure what the preferred placement is. I had noticed this on a couple of repositories that @notwaldorf had made like [mojibrag](https://github.com/notwaldorf/mojibrag/blob/master/index.html#L122). 

My guess is that it would give the basic styling and layout quicker. This would come in handy when adding a loader into the `index.html` page. 

I can revert that change if it is better to leave at the top.

**Comment by jay8t6** [comment]
+1

**Comment by robdodson** [comment]
I think, since the import is async, it should start fetching but still allow the page to move on to rendering the critical styles. This could lead to FOUC though since my-app will no longer block rendering. If you're using critical styles to start painting a shell earlier then that's fine (good, in fact) but if you're not planning for that and just carelessly putting things in index.html then the page will flicker a bit

**Comment by robdodson** [comment]
I'm cool with merging this. My only request would be that you switch from using absolute paths to using relative paths. We just updated the current master of PSK to use relative paths because it helps out a bit with cordova/electron. Still working on a fixes for those folks but it seemed to be an improvement so might as well do it here

**Comment by stramel** [comment]
@robdodson I have change the paths from absolute to relative paths according to the #940 PR that just got merged into master a bit ago. Would you like me to squash the commits before it is merged?

**Comment by stramel** [comment]
I am getting an error when the Travis Build runs. I'm not sure how to fix this issue.

image

**Comment by robdodson** [comment]
@stramel that might just be a travis/github quirk that'll sort itself out when we run it again. You don't need to squash your changes, I can do it in GitHub now

**Comment by stramel** [comment]
@robdodson Anything left that I need to address?

**Comment by robdodson** [comment]
sorry for the delay, got caught up in chrome dev summit. Just checking with the team to see why iron-resizable-behavior keeps failing

**Comment by robdodson** [comment]
OK no clue why that line is failing. It works fine locally. Going to go ahead and merge so we're not blocked on this.

**Pull request merged**
