### PR TITLE
Stop watching changes on bower_componenets

### LINKED ISSUE #681: WATCH HTML - node.exe high CPU consumption on gulp serve
Compare to all previous version of PSK including 1.2.0rc,
in 1.2.2 when __gulp serve__ is running CPU consumption (on Windows 7) increase:
from __0%__-__1%__ to __20%__-__27%__

seems to be because this line:
gulp.watch(['app/**/*.html'], reload);

### PR DESCRIPTION
**Pull request by e111077**
Fixes #681

### CODE REVIEW

**Comment by samccone** [comment]
:+1: lgtm :)

**Comment by samccone** [comment]
@e111077 just FYI typically we like to have at least 2 :+1:'s from core maintainers.

The merge responsibility typically happens from the last person to +1 it.

Thanks for the PR

**Comment by abdonrd** [comment]
Thanks @e111077!

**Comment by vitoexe** [comment]
@e111077 grrr... Why, You did it?!

Instead of getting me time do it! Seems to by my solution  #681
Maybe I'm wrong but it is not fair...

**Comment by e111077** [comment]
Sorry about that; I've been on issue busting mode and was mindlessly resolving issues. I did not see the times these comments were posted and assumed it was a long-open issue. I definitely should have given you more time to implement it.

**Comment by samccone** [comment]
@e111077 we really appreciate the bug report and patch you suggested. I would really love to have your help on a few other issues if you are interested! 

https://github.com/PolymerElements/polymer-starter-kit/issues?q=is%3Aopen+is%3Aissue+label%3Agood-first-bug

Thanks again

**Comment by e111077** [comment]
@samccone sure thing; I'll try to hit them asap.

**Pull request merged**
