### PR TITLE
added simplified Chinese README link

### PR DESCRIPTION
**Pull request by unbug**
added simplified Chinese README link

### CODE REVIEW

**Comment by unbug** [comment]
Don't understand why it's failed the test

**Comment by addyosmani** [comment]
Could you squash your commits?

**Comment by arthurvr** [comment]
Should we really add translations? Not IMHO. Mostly results in a pain later on. _Are they still up to date? Who will keep them up to date? Is the translation even good and correct?_

**Comment by unbug** [comment]
@addyosmani Do you mean I should not do any PR like this?Of course.I understand,sorry about this ;)

**Pull request closed without merging**
