### PR TITLE
Change order of `elements.html`

### LINKED ISSUE #109: elements.html should be sorted alphabetically
Hi, one of the first things I do is sort my HTML imports alphabetically like so:

```javascript
<link rel="import" href="../bower_components/iron-flex-layout/classes/iron-flex-layout.html">
<link rel="import" href="../bower_components/iron-icons/iron-icons.html">
<link rel="import" href="../bower_components/iron-pages/iron-pages.html">
<link rel="import" href="../bower_components/iron-selector/iron-selector.html">
<link rel="import" href="../bower_components/paper-drawer-panel/paper-drawer-panel.html">
<link rel="import" href="../bower_components/paper-header-panel/paper-header-panel.html">
<link rel="import" href="../bower_components/paper-icon-button/paper-icon-button.html">
<link rel="import" href="../bower_components/paper-item/paper-item.html">
<link rel="import" href="../bower_components/paper-material/paper-material.html">
<link rel="import" href="../bower_components/paper-menu/paper-menu.html">
<link rel="import" href="../bower_components/paper-styles/paper-styles-classes.html">
<link rel="import" href="../bower_components/paper-toast/paper-toast.html">
<link rel="import" href="../bower_components/paper-toolbar/paper-toolbar.html">
<link rel="import" href="../bower_components/platinum-sw/platinum-sw-cache.html">
<link rel="import" href="../bower_components/platinum-sw/platinum-sw-register.html">
```
This make it easy to add new imports without scanning for duplicates. 

Currently, I do this manually. Is there an easy way to do this with Gulp. Yes, I recognize this may be the worlds smallest enhancement request ;)

### PR DESCRIPTION
**Pull request by arthurvr**
This seems like the logical order to me. Ordered per group, alphabetically.

Fix #109

### CODE REVIEW

**Comment by addyosmani** [comment]
Changes LGTM. @ValueBC - does this sufficiently solve your original feature request?

**Comment by ValueBC** [comment]
Hi, not sure what LGTM means but I assume the idea is acceptable.

**Comment by arthurvr** [comment]
> Hi, not sure what LGTM means but I assume the idea is acceptable.

It's an abbreviation for "looks good to me" :)

**Comment by addyosmani** [comment]
Landed via 46a7d7002b1dd94317fc22a08a537a6da7b1b699

**Comment by addyosmani** [comment]
Thanks again @arthurvr!

**Pull request closed without merging**
