### PR TITLE
Indent all html files

### PR DESCRIPTION
**Pull request by abdonrd**

### CODE REVIEW

**Comment by robdodson** [comment]
Did you run the files through a tool like sublime beautify?

**Comment by abdonrd** [comment]
No, I indent the `head` and `body` manually.

**Comment by samccone** [comment]
To merge this change I would like to see the following:

1. An automated lint process that will cause failures on CI if the indentation is wrong
2. The equivalent of jshint but for html

----

The reason why this change is not scalable as it stands is that the burden of formatting verification will fall on whoever reviews the next change, and tiny formatting nits are often not caught.

Thanks for the interest and PR here @abdonrd, let me know your thoughts on what I said ^

**Comment by abdonrd** [comment]
@cdata I am strongly in favor of automating this. 👍

Maybe [HTMLHint](https://github.com/yaniswang/HTMLHint)? There are an [Atom package](https://atom.io/packages/linter-htmlhint).

And a style guide for PSK and Polymer elements would be awesome.

**Comment by cdata** [comment]
@abdonrd We will be adding Polylint to our elements' CI flow in the future, but I don't think that it will be picky about indentation issues. @garlicnation can comment on if that is in the cards or not.

When it comes to picking a linter for automation, the most important thing IMO is that its rules are configurable. HTML linters can be particularly picky about some details (e.g., doctype validation) and I don't think we should force ourselves to adhere strictly to everything the linter prefers without some discussion.

**Comment by abdonrd** [comment]
@cdata Personally, I like the idea that in a project, all follow the same style guidelines. Especially when the project has a big community. But I also understand your position.

**Comment by cdata** [comment]
@abdonrd I completely agree. What I mean to say is that the style guidelines should be chosen by the project's contributors, not by the linter.

**Comment by abdonrd** [comment]
@cdata ah, okey! I completely agree too. :grin:

**Comment by samccone** [comment]
going to close this for now, @abdonrd feel free to open an issue with some possible linters for us, or any thoughts around this.

Thanks a bunch for this initial spike of work!

**Pull request closed without merging**
