### PR TITLE
added gulp task for deployment

### PR DESCRIPTION
**Pull request by VikramTiwari**
on gh-pages

### CODE REVIEW

**Comment by addyosmani** [comment]
@samccone temporarily assigning to you as you mentioned an interest in deployment tasks at the next team sync. Should something like this exist in recipe form or be baked in?

**Comment by samccone** [comment]
I think it can be baked in... sort like

* clone the repo
* edit the project
* deploy your project

thoughts?

**Comment by chuckh** [comment]
I think it should be baked in.  To do this we need to address routing issues with Github pages (not running from root). See https://github.com/PolymerElements/polymer-starter-kit/issues/459#issuecomment-153105185 for details for what needs to be done to make this work. You can see example at http://proplanr.github.io/polymer-starter-kit.

**Comment by samccone** [comment]
Hey @VikramTiwari thanks a million for this PR, it seems like @chuckh is building on top of this work in #481 so I am going to close this PR 

Thanks for getting the ball rolling on this one, awesome stuff :+1:

**Comment by VikramTiwari** [comment]
That works! :+1:

**Pull request closed without merging**
