### PR TITLE
Revert "Enabling caching of node_modules on Travis"

### PR DESCRIPTION
**Pull request by samccone**
Reverts PolymerElements/polymer-starter-kit#775

### CODE REVIEW

**Comment by TimvdLippe** [comment]
What was the reason to revert this change?

**Comment by samccone** [comment]
it was causing CI to fail.

**Comment by abdonrd** [comment]
We know why it failed? The https://github.com/PolymerElements/polymer-starter-kit/pull/795 fixes?

**Comment by TimvdLippe** [comment]
I think indeed the failures are fixed in #795, as the builds show that `apt-get install` actually failed (and not `npm install`) https://travis-ci.org/PolymerElements/polymer-starter-kit/jobs/122548438

**Pull request merged**
