### PR TITLE
Drawer will hide on page change, unless drawer is persistent

### PR DESCRIPTION
**Pull request by mercmobily**
Hi,

The title says it all!
It's only has minor modifications, but with great gains.
I gave an ID to the drawer so that I could refer to it with `this.$.drawer`. I hope that's accetable!

Merc.

### CODE REVIEW

**Comment by jsilvermist** [comment]
Why use a (2 way) binding, why not just set `this.$.drawer.opened = false;`?

**Comment by mercmobily** [comment]
@jsilvermist Sorry, it was a leftover from my code, mended to avoid the two-way binding silliness

**Comment by mercmobily** [comment]
I am not a fan of doing a DOM query (and two of them) when you can just use the ID.
I think it's more readable without the brackets... and assigning the property feels cleaner!
I might be wrong...

**Comment by H3dz** [comment]
Yes, you're right, looks like assigning the property is the way to do it.

If you look at app-drawer there's actually a "close" method that does exactly that.

`if (!this.$.drawer.persistent) this.$.drawer.close();`

**Comment by mercmobily** [comment]
Absolutely agreed -- I didn't realise there was a `close()` method. Mended!

**Comment by mercmobily** [comment]
(this is gonna have to be the most discussed one-liner in the history of Polymer :D )

**Comment by robdodson** [comment]
Thanks @mercmobily and sorry for not getting to this sooner (i'm traveling at the moment).
Would you mind adding braces to the `if` statement? That matches the style that we use for the rest of our code.

**Comment by mercmobily** [comment]
Sure!

1)
Like this:

    if (!this.$.drawer.persistent){ this.$.drawer.close(); }

Or like this:

    if (!this.$.drawer.persistent) {
      this.$.drawer.close();
    }

?
I am assuming it's the latter. Committed already -- let me know if I got it right :D
I have a newline after `this.page = page || 'view1';` as it's a separate issue logically speaking. Again, let me know if you agree.

2) Do you have a link at the style guide?

3) Do you have a beautifier that will make sure the code follows the standards?

Ta!

**Comment by robdodson** [comment]
Thanks!

> 2) Do you have a link at the style guide?

No but I should come up with one.

> 3) Do you have a beautifier that will make sure the code follows the standards?

No but we should probably add one. I've [opened an issue to do so](https://github.com/PolymerElements/polymer-starter-kit/issues/933).

**Comment by mercmobily** [comment]
Yay!!! My first pull request accepted into Polymer!!
Hopefully many many more to come! :D

(I am going to work on file attachments and iron-ajax soon!)

**Comment by robdodson** [comment]
👍

**Pull request merged**
