### PR TITLE
Update dependencies & fix linting (fixes #488 and fixes #489)

### LINKED ISSUE #488: Out of date dependencies
Check here: https://david-dm.org/PolymerElements/polymer-starter-kit#info=devDependencies&view=table

### LINKED ISSUE #489: Gulp not working in master
Hello i cloned the last version from master and gulp is not working.

this is the outcome: 

/usr/local/bin/node /usr/local/lib/node_modules/gulp/bin/gulp.js --color --gulpfile /Users/alberto/work/github/polymer-starter-kit/gulpfile.js default
[10:16:45] Using gulpfile ~/work/github/polymer-starter-kit/gulpfile.js
[10:16:45] Starting 'clean'...
[10:16:45] Finished 'clean' after 449 ms
[10:16:45] Starting 'default'...
[10:16:45] Starting 'copy'...
[10:16:45] Starting 'styles'...
[10:16:46] styles all files 98 B
[10:16:46] Finished 'styles' after 1.11 s
[10:16:48] copy all files 13.04 MB
[10:16:48] Finished 'copy' after 3.12 s
[10:16:48] Starting 'elements'...
[10:16:48] Finished 'elements' after 6.81 ms
[10:16:48] Starting 'lint'...
[10:16:50] Starting 'images'...
[10:16:50] Starting 'fonts'...
[10:16:50] Starting 'html'...
[10:16:51] Finished 'fonts' after 611 ms

/Users/alberto/work/github/polymer-starter-kit//Users/alberto/work/github/polymer-starter-kit/gulpfile.js
  line 208  col 163  Line must be at most 100 characters

  ⚠  1 warning

[10:16:53] 'lint' errored after 4.28 s
[10:16:53] Error in plugin 'gulp-jshint'
Message:
    JSHint failed for: gulpfile.js
[10:16:53] 'default' errored after 7.41 s
[10:16:53] Error in plugin 'run-sequence'
Message:
    An error occured in task 'lint'.
[10:16:53] html all files 52.27 kB
[10:16:53] Finished 'html' after 2.64 s
[10:16:53] gulp-imagemin: Minified 6 images (saved 494 B - 1.4%)
[10:16:53] images all files 35.41 kB
[10:16:53] Finished 'images' after 3.07 s

Process finished with exit code 1

splitting the line 208 in :
glob(['index.html', './', 'bower_components/webcomponentsjs/webcomponents-lite.min.js', 
    '{elements,scripts,styles}/**/*.*'], {cwd: dir}, function(error, files) {

fixed the issue

### PR DESCRIPTION
**Pull request by addyosmani**
This now makes `gulp` pass for #489 and updates dependencies for #488. Verified works locally:

```
$ gulp
[12:17:32] Using gulpfile ~/projects/io-workspace/polymer-starter-kit/gulpfile.js
[12:17:32] Starting 'clean'...
[12:17:32] Finished 'clean' after 337 ms
[12:17:32] Starting 'default'...
[12:17:32] Starting 'copy'...
[12:17:33] Starting 'styles'...
[12:17:33] styles all files 98 B
[12:17:33] Finished 'styles' after 567 ms
[12:17:34] copy all files 12.61 MB
[12:17:34] Finished 'copy' after 1.71 s
[12:17:34] Starting 'elements'...
[12:17:34] Finished 'elements' after 4.25 ms
[12:17:34] Starting 'lint'...
[12:17:35] Starting 'images'...
[12:17:35] Starting 'fonts'...
[12:17:35] Starting 'html'...
[12:17:35] Finished 'fonts' after 152 ms
[12:17:37] Finished 'lint' after 2.95 s
[12:17:37] gulp-imagemin: Minified 6 images (saved 494 B - 1.4%)
[12:17:37] images all files 35.41 kB
[12:17:37] Finished 'images' after 2.29 s
[12:17:38] html all files 2.39 MB
[12:17:38] Finished 'html' after 3 s
[12:17:38] Starting 'vulcanize'...
[12:17:42] vulcanize all files 257.89 kB
[12:17:42] Finished 'vulcanize' after 3.37 s
[12:17:42] Finished 'default' after 9.02 s
```
r: @samccone @chuckh (please manually check these updates work on your box :kissing:)

### CODE REVIEW

**Comment by moderndeveloperllc** [comment]
@addyosmani For what it's worth, I'm having issues running `gulp` on this branch:

```
$ gulp
[09:24:21] Using gulpfile ~/Sites/polymer-starter-kit/gulpfile.js
[09:24:21] Starting 'clean'...
$ 
```
It's installing `del` 2.0.2, and I think that is causing issues? maybe? I tried removing all deps, clean the cache, and `npm install && bower install` and still have issues. A slightly older master/ (includes #486) runs fine. That has `del` 1.2.1.

OSX 10.11.1
node 4.2.2
npm 2.14.8
gulp 3.9.0
bower 1.6.5

**Comment by addyosmani** [comment]
Weird. I was running into the exact same issue you were, but clearing out my `node_modules` directory and reinstalling seemed to address it. I'll try reproducing the breakage again.

**Comment by fmauNeko** [comment]
With del 2.0.x the callback doesn't work anymore, because del() now returns a promise.
Replacing the clean task with
```javascript
gulp.task('clean', function() {
  return del(['.tmp', 'dist']);
});
```
does the job.

**Comment by addyosmani** [comment]
Verified locally that this was indeed breaking and the above fix did indeed correct the behaviour. Update incoming.

**Comment by chuckh** [comment]
I found the same problem the above fixed worked for me too.

**Comment by moderndeveloperllc** [comment]
I thought there was some talk about this - issue #452 mentioned this problem.

**Comment by samccone** [comment]
testing

**Comment by chuckh** [comment]
Latest changes worked for me locally.

**Comment by samccone** [comment]
since we updated all of the deps in this one I am doing a fresh npm i just to make sure... since there is a fair bit of risk here

**Comment by samccone** [comment]
woot all good :+1:

**Pull request merged**
