### PR TITLE
Using dist() to manage path of dist

### PR DESCRIPTION
**Pull request by ragingwind**
Using dist() function helps users change path of dist easily where they want

### CODE REVIEW

**Comment by ragingwind** [comment]
I've tested multiple time in local but I couldn't met this error.

**Comment by samccone** [comment]
which error @ragingwind ?

**Comment by ragingwind** [comment]
CI show tests fail

**Comment by samccone** [comment]
oh that is unrelated for the time being :) 


xref https://github.com/PolymerElements/polymer-starter-kit/issues/394

**Comment by samccone** [comment]
@ragingwind would you mind a quick rebase? on this

otherwise ... I am totally :+1:

**Comment by ragingwind** [comment]
I will :)

**Comment by ragingwind** [comment]
@samccone Fixed it

**Comment by samccone** [comment]
LGTM :+1:

**Comment by samccone** [comment]
thanks again @ragingwind :)

**Comment by addyosmani** [comment]
:+1:

**Pull request merged**
