### PR TITLE
 CSS reduction and add header effects

### PR DESCRIPTION
**Pull request by abdonrd**
Before:

may-08-2016 18-27-12

After:

may-08-2016 18-26-44

### CODE REVIEW

**Comment by mercmobily** [comment]
Yes that's about 462804571 times better than my solution...

**Comment by addyosmani** [comment]
LGTM

**Comment by robdodson** [comment]
Thanks @abdonrd

**Comment by abdonrd** [comment]
Yay! :)

**Comment by robdodson** [comment]
I just noticed on desktop this looks pretty weird.

screen shot 2016-05-11 at 3 35 16 pm

**Comment by joryphillips** [comment]
I gotta be honest with everyone. The shrink-on-scroll header title effect is the first thing I disable every time I launch a new project with PSK. _It is really cool_ — and to me seems more appropriate as a 'theme' than as the default configuration.

**Comment by robdodson** [comment]
@joryphillips yeah on second thought I'm inclined to agree. We're going to have add back in CSS to fix this for desktop. May as well go with something simpler to begin with

**Comment by robdodson** [comment]
Did some cleanup ➡️ https://github.com/PolymerElements/polymer-starter-kit/pull/828

**Comment by abdonrd** [comment]
If we can get from [app-header/demo1.html](http://polymerlabs.github.io/app-layout/app-header/demo/demo1.html). Only need to add some more CSS to fix desktop view.

**Comment by chuckh** [comment]
For mobile condensing the header makes better use of the screen real estate. I prefer fixing desktop over removing condensing.

**Comment by abdonrd** [comment]
I'm agree with @chuckh! :)

**Comment by robdodson** [comment]
I was thinking about this a bit in the car this morning. @joryphillips, @samccone, and myself seem to prefer not using the condensing effect and it sounds like @chuckh's concern is primarily around the use of space on mobile.

Would an acceptable compromise be to just not have a giant header, but instead always use a smaller, mobile friendly header. That way the user is likely not in the position of needing to remove a bunch of stuff if they don't like the header. Instead they can add effects if they want.

**Comment by robdodson** [comment]
Basically this: https://polymerlabs.github.io/app-layout/templates/getting-started/

screen shot 2016-05-12 at 9 21 08 am

**Comment by chuckh** [comment]
> Would an acceptable compromise be to just not have a giant header, but instead always use a smaller, mobile friendly header. 

@robdodson make sense to me!

**Comment by abdonrd** [comment]
Makes sense to me too!

**Pull request merged**
