### PR TITLE
Add `npm start` script

### LINKED ISSUE #212: use npm start do start gulp serve
as npm test

### PR DESCRIPTION
**Pull request by arthurvr**
Fix #212

### CODE REVIEW

**Comment by ukkieanna** [comment]
Good

**Comment by chuckh** [comment]
LGTM.

**Comment by addybd** [comment]
you should stay telling people to install gulp global but I think this is good if you just need to use psk once :+1:

**Comment by bppffnn** [comment]
where are you waiting on to merge this @arthurvr

**Comment by arthurvr** [comment]
@bppffnn An lgtm from @addyosmani I guess :p

**Comment by robbbz** [comment]
:+1: ping @addyosmani?

**Pull request closed without merging**
