### PR TITLE
Looks better to have a close icon to close toast

### PR DESCRIPTION
**Pull request by jtvjan**
This may look better than it does now, I already tested it so it works.

### CODE REVIEW

**Comment by jtvjan** [comment]
I signed it!

**Comment by robdodson** [comment]
Hey @jtvjan thanks for the pull request! We're using the Material Design guidelines to dictate our usage of components and they mention that [snackbars/toasts should not contain icons](https://material.google.com/components/snackbars-toasts.html). I think we're going to stick with that guidance for now but thank you again for taking the time to submit the change :)

**Comment by jtvjan** [comment]
Ok. But the '0-1 actions, not dismiss or cancel' section in that very document contradicts the OK button. Not saying that my PR is better, just saying that you might want to remove the OK button altogether.

**Comment by robdodson** [comment]
Hm good point.

**Comment by jtvjan** [comment]
I made that change I said in my previous comment, see #866

**Pull request closed without merging**
