### PR TITLE
Clean project

### PR DESCRIPTION
**Pull request by abdonrd**
I propose remove this unused files, since now the structure is different.
We may be creating as we need.

### CODE REVIEW

**Comment by robdodson** [comment]
Hm that's a question for @samccone and @chuckh. I'm not super familiar with how the travis stuff works

**Comment by abdonrd** [comment]
@robdodson okey!

If we don't write the:

```yml
script:		
  - ./travis-runner.sh
```

Travis will be run `npm test` by default.

And because the structure has changed, the content of `travis-runner.sh` not working. We must to update the it.

**Comment by chuckh** [comment]
I think we should leave them for now as place holders. We will still need them to handle auto deploying to Github and Firebase. Once we get closer to agreeing on the new structure they can be updated.

**Comment by abdonrd** [comment]
While we are not sure how it will be, I think it would be better to have it clean.
We always have the git history and the `master` branch with the previous changes.

**Comment by abdonrd** [comment]
I would also add `gulp lint` in `.travis.yml`:

```yml
before_script:
 ...
  - npm i -g bower gulp
  - bower i
  - gulp lint
```

**Comment by addyosmani** [comment]
> I think we should leave them for now as place holders. We will still need them to handle auto deploying to Github and Firebase. Once we get closer to agreeing on the new structure they can be updated.

I agree with Chuck on this one.

**Comment by abdonrd** [comment]
Then we close it?

**Comment by chuckh** [comment]
Yes. Closing it now.

**Pull request closed without merging**
