### PR TITLE
✂️

### PR DESCRIPTION
**Pull request by notwaldorf**
PTAL 👀  @robdodson @azakus

### CODE REVIEW

**Comment by azakus** [comment]
ISSUE TEMPLATE should stick around. LGTM otherwise.

**Comment by notwaldorf** [comment]
@azakus Done!

**Comment by abdonrd** [comment]
Why remove the licenses?

**Comment by notwaldorf** [comment]
@abdonrd This is what `polymer init starter-kit` generates, which is the user's brand new project, that we didn't write, so _our_ license shouldn't be on it by default

**Comment by notwaldorf** [comment]
Ok after more talking, we should leave the source licenses in and just remove the unused license.txt, so the user can provide their own for new changes. Licenses are hard.

**Comment by robdodson** [comment]
Thanks @notwaldorf !

**Comment by jsilvermist** [comment]
Aww sad =/ I know the license in the files have prevented some groups and companies from being allowed to use it in the past.

**Pull request merged**
