### PR TITLE
Update 404 page

### PR DESCRIPTION
**Pull request by abdonrd**
Reference: https://github.com/PolymerElements/polymer-starter-kit/pull/786#issuecomment-208481801

### CODE REVIEW

**Comment by robdodson** [comment]
LGTM thanks!

**Comment by chuckh** [comment]
:+1:  

Also it would be nice to have a home page `http://localhost:8080/components/polymer-starter-kit/#/` instead routing to `http://localhost:8080/components/polymer-starter-kit/#/art`

**Comment by abdonrd** [comment]
@chuckh yes! Can you send a PR? :smiley:

**Comment by chuckh** [comment]
@abdonrd I will give it a try now.

**Comment by robdodson** [comment]
Hmm that means we need to come up with a design for that page. I'd prefer to stick as close to the current zuperkulblog as possible

**Comment by chuckh** [comment]
@robdodson I understand, but I think having a home page is a common use case like we have in PSK1 and is worth the effort.

**Comment by robdodson** [comment]
Before we spend too much time on that I think it'd be good to get everything else to a near final point and make sure that things are playing nice with the CLI and everyone is happy with the basic shape of the site. In the back of my mind I'm wondering if we're going to end up scrapping stuff as requirements change. We may want PSK to just turn into 1 of many simplified templates that all live in a single repo

**Comment by robdodson** [comment]
Sorry to continue on from that thought a bit. I'm cool with the idea of adding a home page but don't want folks to be annoyed if we end up scrapping that work because we decide we want the template to be something simpler.

**Pull request merged**
