### PR TITLE
Should fix #742

### LINKED ISSUE #742: focus null in neon-animated-pages recipe
"focus null" error after following the neon-animated-pages recipe in the /docs

i think is the "section" in the routing.html file:
document.querySelector('section[data-route="' + selected + '"]').focus();

it´s ok to replace section to "neon-animated" too? (#newbie)
document.querySelector('neon-animatable[data-route="' + selected + '"]').focus();

### PR DESCRIPTION
**Pull request by motss**
Update recipe to handle focus with `neon-animatable`.

### CODE REVIEW

**Comment by samccone** [comment]
:+1: boom nice

**Comment by samccone** [comment]
cc @robdodson

**Comment by vguillou** [comment]
:+1:

**Comment by robdodson** [comment]
Thanks @motss!

**Pull request merged**
