### PR TITLE
Move app-theme.html to styles folder

### LINKED ISSUE #139: Move app-theme.html to styles dir
This file is essentially a stylesheet being shimmed with custom props by `custom-style`. It feels like it should live in `styles`, I keep reflexively looking for it in there. Maybe it's just me, but it feels weird to have it in the `elements` dir

### PR DESCRIPTION
**Pull request by chuckh**
Fixes #139

### CODE REVIEW

**Comment by addyosmani** [comment]
Thanks @chuckh! Is it possible to squash the commits to just https://github.com/chuckh/polymer-starter-kit/commit/778554760cc8fd2a96ff0c9baea377063e19b6b7?

**Comment by chuckh** [comment]
I will look into it. The other commits is how I got my fork up to date with PolymerElements/polymer-starter-kit/ master.

**Comment by addyosmani** [comment]
@chuckh If you could also update the README to point to the new location (there are a few places we reference the older one), I'm happy to squash for you as part of review.

**Comment by addyosmani** [comment]
Landed via ed982342937e0012af5bf7a232276bab19646e04 & ed982342937e0012af5bf7a232276bab19646e04. Thanks @chuckh!

**Pull request closed without merging**
