### PR TITLE
Update polymer init command

### PR DESCRIPTION
**Pull request by ernsheong**

### CODE REVIEW

**Comment by abdonrd** [comment]
@justinfagnani @FredKSchott we should update the PSK README? Or the Polymer CLI should revert to `starter-kit`? Now it only have the Polymer 2 versions.

**Comment by ernsheong** [comment]
Anyone?

**Comment by abdonrd** [comment]
@ernsheong I'm waiting for Justin and/or Fred.

**Comment by justinfagnani** [comment]
Since we pull starter kit directly from Github, let's do this update for now, then move to plain `starter-kit` with a change to CLI (and reverting this).

**Comment by justinfagnani** [comment]
So LGTM

**Comment by ernsheong** [comment]
Thanks. I imaging this would be the starting point for most newbies to Polymer. So it's kinda crucial to update the doc to ensure a smooth onboarding...

**Comment by abdonrd** [comment]
Thanks both!

**Pull request merged**
