### PR TITLE
🍕 Add polymer imports to default elms

### LINKED ISSUE #89: Should elements import polymer at the top
I noticed `my-list` and `my-greeting` don't have imports for polymer at the top of their definitions. I was wondering if that was done on purpose, and if not, if it would be ok to add those?

### PR DESCRIPTION
**Pull request by samccone**
Fixes #89

### CODE REVIEW

**Comment by ebidel** [comment]
:100:

**Comment by samccone** [comment]
chatting async with @azakus about resolving the weirdness with WCT... however it should not be a blocked :goat:

**Comment by chuckh** [comment]
LGTM2. Another pr can be made for WCT, maybe a setting in 'wct.conf.json' can fix the 404 messages.

**Comment by samccone** [comment]
@chuckh resolved the test issue :)

**Comment by chuckh** [comment]
@samccone nice work :100:

**Comment by addyosmani** [comment]
LGTM3. Thanks @samccone!

**Pull request merged**
