### PR TITLE
Flatten structure

### PR DESCRIPTION
**Pull request by robdodson**
@chuckh @abdonrd @addyosmani PTAL

### CODE REVIEW

**Comment by abdonrd** [comment]
LGTM!

**Comment by abdonrd** [comment]
Opps! @robdodson update the `polymer.json`.

**Comment by robdodson** [comment]
good catch

**Comment by chuckh** [comment]
Nice catch @abdonrd! 😄 .  LGTM once polymer.json is fixed.

**Comment by robdodson** [comment]
Updated

**Comment by abdonrd** [comment]
Now LGTM! :)

**Comment by chuckh** [comment]
Nice work @rob and @abdonrd 💯

**Pull request merged**
