### PR TITLE
Lock firefox version down

### PR DESCRIPTION
**Pull request by samccone**
in an attempt to get the tests passing again...

---

firefox 43 was the issue

### CODE REVIEW

**Comment by robdodson** [comment]
cc @azakus

**Comment by azakus** [comment]
Maybe you can tell me what the actual issue is?

**Comment by robdodson** [comment]
Failing wct tests because of Firefox (https://travis-ci.org/PolymerElements/polymer-starter-kit/jobs/97494157).

Seems related to https://github.com/Polymer/web-component-tester/issues/248#issuecomment-165189016

**Comment by azakus** [comment]
Just update WCT to 4: https://travis-ci.org/PolymerElements/polymer-starter-kit/jobs/97523108

**Comment by samccone** [comment]
Hi @azakus thanks for asking, let me tell you what the observed "actual" issue is.

The "issue" which I bisected on CI is that selenium is unable to connect to firefox 43, however it is able to connect to firefox 42, so for the short term I have opted to lock down the firefox version so that our test suite is still passing while the issue is resolved upstream.

In my mind this is a good option because having failing CI tests removes a level of trust from people in the project as well as loses trust from other contributors and encourages people to ignore CI which we want to avoid.

**Comment by samccone** [comment]
before we upgrade to 4.x I would be interested in seeing the breaking changes so we can be prepared to deal with the issues here on PSK

https://github.com/Polymer/web-component-tester/blob/master/CHANGELOG.md

**Comment by robdodson** [comment]
Yeah let's merge this temporarily to get back on track and work on wct 4 in a separate PR

**Comment by samccone** [comment]
I have created a new issue to track the upgrade
https://github.com/PolymerElements/polymer-starter-kit/pull/607

For now I am +1 to landing this "stopgap"

**Pull request merged**
