### PR TITLE
Separate theming file for app, in line with other page files and easier to deal with/change

### PR DESCRIPTION
**Pull request by mercmobily**
It really bothered me that PSK2's theming options were inline within psk-app.html. I like the fact that we no longer use a "general" CSS that gets included, and the fact that CSS is set at element-level.
I think it makes a lot more sense this way. Plus, the app looks better too...

### CODE REVIEW

**Comment by abdonrd** [comment]
I'm not sure if it is the best option, but I prefer a theme file with the colors and little else, not all the CSS.

**Comment by mercmobily** [comment]
So, the app-theme.html could be something like this, ONLY to include the general app-wise CSS custom properties (and leaving the CSS belonging to the `psk-app.html` where it is now..._ 

The rationale is that changes here will affect the WHOLE app, whereas changes to psk-app.html will only affect the "app" element as such (which makes sense).

    
    <link rel="import" href="../../bower_components/polymer/polymer.html">
    <link rel="import" href="../../bower_components/paper-styles/color.html">

    
    <dom-module id="app-theme">
      <template>
        <style>
          :host {

            /* PSK2-specific custom properties */
            --app-primary-color:  var(--paper-indigo-500);

            /* Default paper custom properties */
            --primary-text-color: var(--paper-grey-900);
            --primary-background-color: #ffffff;
            --secondary-text-color: #737373;
            --disabled-text-color: #9b9b9b;
            --divider-color: #dbdbdb;
            --primary-color: var(--paper-indigo-500);
            --light-primary-color: var(--paper-indigo-100);
            --dark-primary-color: var(--paper-indigo-700);
            --accent-color: var(--paper-pink-a200);
            --light-accent-color: var(--paper-pink-a100);
            --dark-accent-color: var(--paper-pink-a400);
            }
        </style>
      </template>
    </dom-module>

I cannot make a PR because there is still #825 pending...

**Comment by mercmobily** [comment]
@abdonrd  I agree. I updated the PR so that it does just that. It seems to make sense now...

**Comment by robdodson** [comment]
We've totally revamped PSK2 so unfortunately this PR is no longer compatible.

I'm leaving open issues related to theming as we decide on what approach we want to use. Thanks for the PR @mercmobily. Coming up with theming guidance is the next p0 for us working on PSK

**Pull request closed without merging**
