### PR TITLE
Add dotfile warning to readme

### PR DESCRIPTION
**Pull request by robdodson**
Proposing this as an alternative to https://github.com/PolymerElements/polymer-starter-kit/pull/555
Hopefully improves https://github.com/PolymerElements/polymer-starter-kit/issues/544

Addy has added a write up to the release notes, and hopefully adding this warning to the README also makes it very clear that the user should be on the lookout for those dotfiles. I would much prefer we try to go this route and see if folks still have problems vs. adding new code to the gulpfile to check for missing stuff.

`<tangent>`
I've been feeling that the gulpfile is getting really large and difficult for users to modify and, equally important, for us to safely maintain. https://github.com/PolymerElements/polymer-starter-kit/pull/568 is an attempt to correct some of this. I'd love if we could do some aggressive pruning to get it down as small as possible so it isn't so intimidating.
`</tangent>`

### CODE REVIEW

**Comment by addyosmani** [comment]
Commenting on the tangent: I agree. This is actually an opinion I hold with both Polymer Starter Kit and Web Starter Kit. The Gulpfiles are almost unwieldy. One thing we may explore next quarter is having a split Gulpfile tasks repo that both projects can pick and choose from. This may reduce complexity and overlap whilst making it easier to reason what is going on.

**Comment by chuckh** [comment]
Change to readme LGTM. :+1: 

I agree with @robdodson and @addyosmani  on <tangent>.  The gulp file is complex, pruning and splitting tasks out in separate files could make it simpler to understand and maintain. Having a shared repo for both PSK and WSK  makes sense.

Polymer Starter Kit Plus has split out gulp tasks. See https://github.com/StartPolymer/polymer-starter-kit-plus/tree/master/tasks.

**Comment by addyosmani** [comment]
I'm :+1: on readme change too (thanks for reviewing, @chuckh!). @samccone do you feel that a README note would be sufficient here or that there's enough chance that folks aren't going to read it that having a build-time warning is better?

**Comment by samccone** [comment]
I am for this change, however I am also for the gulpfile change, I think they are both very valuable to two different sets of people

**Comment by chuckh** [comment]
> I am for this change, however I am also for the gulpfile change, I think they are both very valuable to two different sets of people

I agree. Landing this. Can handle error message with pr #555.

**Pull request merged**
