### PR TITLE
Remove linting

### PR DESCRIPTION
**Pull request by samccone**
People are way too confused by this. Going to back this out until we figure out a better strategy

https://github.com/PolymerElements/polymer-starter-kit/issues/506
https://github.com/PolymerElements/polymer-starter-kit/issues/531
https://github.com/PolymerElements/polymer-starter-kit/issues/596

(and many more)

### CODE REVIEW

**Comment by robdodson** [comment]
SGTM. @addyosmani wdyt?

**Comment by abdonrd** [comment]
A shame, I liked linting. :sob:

**Comment by JosefJezek** [comment]
Unified linting is must have feature for developers on PSK ;-)

**Comment by klarkc** [comment]
I like the liting feature, it's essential for the good quality of the code. But while there is not a clear way to refer directly the issue file, maybe the removal is the right thing to be done.

**Comment by addyosmani** [comment]
I'm sad to see this go for now, but agree it's the right call. Let's explore how we can better redo linter support for the upcoming refactor.

**Comment by samccone** [comment]
I am in agreement with you @abdonrd @JosefJezek @klarkc , however it seems like a large number of the users of PSK have never used a tool like jshint or jscs and are very confused about what is wrong with their code.

Due to the above fact, this generates a lot of noise and maintenance work for us on this repo. This is not a failure of our users, but rather a poor assumption on my part around how users will interact with our tooling.

**Comment by robdodson** [comment]
For what it's worth, we're planning on redoing the build process so it's much easier to add in optional modules. Linting is going away for now but hopefully this is only temporary

**Comment by robdodson** [comment]
@addyosmani I'm a bit confused. This PR was closed by e937a3d but that didn't remove linting unless perhaps the history got rewritten somewhere..? That commit is monstrous

**Comment by felixzapata** [comment]
The problem with the lint process using JSCS is that the original task does not extract the script code like jshint does (jshint is more clear to show the line number of the error). 

Due to this reason, it was necessary to pass to a previous task to extract the script code (this task creates some temp files for each piece of script code).

**Pull request closed without merging**
