### PR TITLE
Fixes #147: use paper-icon-button for drawer menu

### LINKED ISSUE #147: Question about menu button
Looking at the default navigation menu button (https://github.com/PolymerElements/polymer-starter-kit/blob/master/app/index.html#L91, I'm really curious about why it uses:

```
<button tabindex="1" id="paperToggle" paper-drawer-toggle>
  <iron-icon icon="menu" paper-drawer-toggle></iron-icon>
</button>
```

instead of this (or something similar):

```
<paper-icon-button icon="menu" paper-drawer-toggle></paper-icon-button>
```

because this way it would look and feel consistent with the other provided default buttons in the toolbar - would that not be preferable/consistent with MD?

### PR DESCRIPTION
**Pull request by addyosmani**
Review from layout perspective: @chuckh 
Review from user: @kbwatts

### CODE REVIEW

**Comment by kbwatts** [comment]
LGTM!

A11y keys etc work as expected :+1:

**Comment by chuckh** [comment]
@addyosmani the left margin of the paper-icon-button is off by 4px.  You need to remove

```
  #paperToggle {
    border: none;
    color: var(--drawer-menu-color);
    background-color: transparent;
    padding: 12px;
    margin: 4px 4px 4px -14px;
  }
```
from app-style.html. It is no longer need and fixes the left margin.

Once this done should be go to go.

**Comment by addyosmani** [comment]
Thanks for reviewing @chuckh. Made the change and dropped the ID for this as it no longer appears to be needed. PTAL whenever it is convenient :)

**Comment by chuckh** [comment]
LGTM. :+1:

**Comment by addyosmani** [comment]
Thanks!

**Comment by arthurvr** [comment]
Looks good to me.

**Comment by addyosmani** [comment]
Landed via 6a3eb99f8fc9e6af00c50463cafc28c487b23380

**Comment by kbwatts** [comment]
Nice one @chuckh :+1:

**Pull request closed without merging**
